// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsmi0fiR0HCGchabg7iXZrdm2HEVhoArY',
    appId: '1:745087925546:android:239a740029b22f7fcff253',
    messagingSenderId: '745087925546',
    projectId: 'gdg-team-and-management-49978',
    storageBucket: 'gdg-team-and-management-49978.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnlGioNMy8arpdPzGHjRAN8JSdPnbrG20',
    appId: '1:745087925546:ios:80a2d5909ec51d1acff253',
    messagingSenderId: '745087925546',
    projectId: 'gdg-team-and-management-49978',
    storageBucket: 'gdg-team-and-management-49978.firebasestorage.app',
    iosBundleId: 'com.example.googleDeveloperApp',
  );
}

//Platform  Firebase App Id
//android   1:745087925546:android:239a740029b22f7fcff253
//ios       1:745087925546:ios:80a2d5909ec51d1acff253

// MD5: C2:C6:3F:BB:12:5E:AC:19:EE:D5:BC:E1:37:99:10:64
// SHA1: BD:7D:70:3A:B2:BB:3E:ED:25:FE:19:5E:A4:88:D0:EE:D2:44:2E:22
// SHA-256: 07:B6:3D:A5:94:D1:D7:29:FE:42:46:B7:DE:3E:4B:94:48:BE:F0:61:93:3F:F6:75:70:95:CE:58:7F:89:0D:54
// Valid until: Saturday, 1 August 2054